version: "3"
services:
  #  Create a service named db.
  share-a-ride-db:
    #   Use the Docker Image postgres. This will pull the newest release.
    image: "postgres"
    #   Give the container the name my_postgres. You can changes to something else.
    container_name: "share-a-ride-db"
    #   Setup the username, password, and database name. You can changes these values.
    environment:
      - POSTGRES_USER=share-a-ride
      - POSTGRES_PASSWORD=share-a-ride
      - POSTGRES_DB=share-a-ride
    #   Maps port 54320 (localhost) to port 5432 on the container. You can change the ports to fix your needs.
    ports:
      - "5491:5432"
    #   Set a volume some that database is not lost after shutting down the container.
    #   I used the name postgres-data but you can changed it to something else.
    volumes:
      - ./postgres-data:/var/lib/postgresql/share-a-ride-db

  pgadmin:
    container_name: "share-a-ride-pgadmin4"
    image: "dpage/pgadmin4"
    restart: "always"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "5030:80"